# Generated by Django 4.2.1 on 2024-08-15 16:21

import cards_app.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doi', models.TextField(null=True, unique=True, verbose_name='DOI')),
                ('title', models.TextField(null=True, verbose_name='Название')),
                ('abstract', models.TextField(null=True, verbose_name='Анотация')),
                ('file', models.FileField(null=True, upload_to=cards_app.models.get_upload_to, validators=[cards_app.models.validate_pdf_extension, cards_app.models.validate_file_size], verbose_name='Файл цитирования')),
                ('file_publication', models.FileField(null=True, upload_to=cards_app.models.get_upload_to, validators=[cards_app.models.validate_pdf_extension, cards_app.models.validate_file_size], verbose_name='Файл публикации')),
                ('citation_url', models.TextField(null=True, verbose_name='Данные для цитирования')),
                ('journal_name', models.TextField(null=True, verbose_name='Название журнала')),
                ('publication_year', models.IntegerField(null=True, verbose_name='Год')),
                ('volume', models.IntegerField(null=True, verbose_name='Том')),
                ('page_numbers', models.CharField(max_length=20, null=True, verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Прямое описание статьи',
                'verbose_name_plural': 'Прямые описания статьи',
                'db_table': 'article_meta',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя автора')),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Ключевое слово')),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='RequiredBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Публикационная база для индексирования',
                'verbose_name_plural': 'Публикационные базы для индексирования',
                'db_table': 'required_base',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scicoins', models.IntegerField(choices=[('300', '300')], verbose_name='Кол-во для оплаты тарифа')),
                ('period', models.IntegerField(choices=[('3', '3')], null=True, verbose_name='Кол-во мес')),
            ],
            options={
                'verbose_name': 'Тарифы',
                'verbose_name_plural': 'Тарифы',
                'db_table': 'tariff',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Область науки',
                'verbose_name_plural': 'Области науки',
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_exchangable', models.BooleanField(default=False, verbose_name='Обмен статьи')),
                ('is_active', models.BooleanField(default=False, verbose_name='Архив')),
                ('theme', models.TextField(verbose_name='Название')),
                ('cart_number', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.articlemeta', verbose_name='Описание статьи')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards_app.requiredbase', verbose_name='Публикационная база для индексирования')),
                ('category', models.ManyToManyField(null=True, to='cards_app.category', verbose_name='Категория')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.tariff', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'db_table': 'cards',
            },
        ),
    ]
