# Generated by Django 4.2.1 on 2024-08-15 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='articlemeta',
            name='authors',
            field=models.ManyToManyField(blank=True, to='cards_app.authors', verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='articlemeta',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='cards_app.keywords', verbose_name='Ключевые слова'),
        ),
    ]
