# Generated by Django 4.2.1 on 2024-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.IntegerField(choices=[(3, '3')], null=True, verbose_name='Кол-во мес'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='scicoins',
            field=models.IntegerField(choices=[(300, '300')], verbose_name='Кол-во для оплаты тарифа'),
        ),
    ]
