# Generated by Django 4.2.1 on 2024-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0005_alter_tariff_scicoins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.IntegerField(choices=[(0, '0'), (3, '3'), (6, '6'), (9, '9'), (12, '12')], null=True, verbose_name='Кол-во мес'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='scicoins',
            field=models.IntegerField(choices=[(0, '0'), (300, '300'), (500, '500'), (100, '100')], verbose_name='Кол-во для оплаты тарифа'),
        ),
    ]
