# Generated by Django 4.2.1 on 2024-08-15 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40')], default=0, verbose_name='Код статуса')),
                ('name', models.TextField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('rejected', 'Отклонено')], verbose_name='Название статуса')),
                ('description', models.TextField(verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус обращения в ТП',
                'verbose_name_plural': 'Статусы обращения в ТП',
                'db_table': 'support_status',
            },
        ),
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Назание типа')),
                ('name_ru', models.TextField(null=True, verbose_name='Назание типа')),
                ('name_en', models.TextField(null=True, verbose_name='Назание типа')),
                ('description', models.TextField(verbose_name='Описание типа')),
            ],
            options={
                'verbose_name': 'Тип обращения в ТП',
                'verbose_name_plural': 'Типы обращения в ТП',
                'db_table': 'support_type',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('narrative', models.TextField(verbose_name='Запрос')),
                ('response', models.TextField(null=True, verbose_name='Ответ')),
                ('support_number', models.IntegerField(null=True)),
                ('declarer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarer_user', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.offers', verbose_name='Заказ')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter_user', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_app.supportstatus', verbose_name='Статус')),
                ('type_support', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='support_app.supporttype', verbose_name='Тип поддержки')),
            ],
            options={
                'verbose_name': 'Обращение в ТП',
                'verbose_name_plural': 'Обращения в ТП',
                'db_table': 'support',
            },
        ),
    ]
