# Generated by Django 4.2.1 on 2024-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstatus',
            name='description',
            field=models.TextField(verbose_name='Описание статуса'),
        ),
    ]
