# Generated by Django 4.2.1 on 2024-08-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_alter_supportstatus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstatus',
            name='code',
            field=models.IntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40')], default=0, verbose_name='Код статуса'),
        ),
    ]
