# Generated by Django 4.2.1 on 2024-08-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Роль-Право', 'verbose_name_plural': 'Роли-Права'},
        ),
    ]
