# Generated by Django 4.2.1 on 2024-08-15 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доказательство',
                'verbose_name_plural': 'Доказательства',
                'db_table': 'evidence',
            },
        ),
        migrations.CreateModel(
            name='OffersStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(choices=[(1, 'отклик'), (2, 'цитирование'), (3, 'ожидание'), (4, 'публикация'), (5, 'откат')], default=0, verbose_name='Код статуса')),
                ('name', models.TextField(verbose_name='Название статуса')),
                ('name_ru', models.TextField(null=True, verbose_name='Название статуса')),
                ('name_en', models.TextField(null=True, verbose_name='Название статуса')),
                ('description', models.TextField(verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
                'db_table': 'offers_status',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_at', models.DateTimeField(null=True)),
                ('barter_is', models.BooleanField(default=False)),
                ('offer_number', models.IntegerField(null=True)),
                ('barter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_barter', to='cards_app.cards')),
                ('barter_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_barter', to='offers_app.offers')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='cards_app.cards', verbose_name='Карточки')),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.evidence')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'offers',
            },
        ),
    ]
