# Generated by Django 4.2.1 on 2024-08-15 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards_app', '0002_initial'),
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='perfomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.articlemeta', verbose_name='Описание статьи'),
        ),
    ]
