# Generated by Django 4.2.1 on 2024-08-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='status_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_customer', to='offers_app.offersstatus'),
        ),
        migrations.AddField(
            model_name='offers',
            name='status_executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_executor', to='offers_app.offersstatus'),
        ),
    ]
